import { IsString } from 'class-validator';

export class VerifyPaymentDto {
  /**
   * The payment reference generated by the platform (PAY-...) or the
   * Paystack gateway reference, depending on context.
   */
  @IsString()
  reference!: string;
}